packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': false
  better-sqlite3: true
  esbuild: false
  msgpackr-extract: false
  prisma: false
  sharp: false
minimumReleaseAgeExclude:
  - openai@6.44.0
